version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: codechella-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-codechella_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Info@123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - codechella_postgres_data:/var/lib/postgresql/data

volumes:
  codechella_postgres_data:
